name: ultimate-nest
version: '2'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - 'db_data:/var/lib/postgresql/data'
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  api-gateway:
    depends_on:
      - db
      - redis
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      tags:
        - beta
      args:
        - APP=api-gateway
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
    restart: always
    ports:
      - 3000:3000

  auth:
    depends_on:
      - db
    container_name: auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      tags:
        - beta
      args:
        - APP=auth
    env_file:
      - .env
    restart: always

volumes:
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./docker/volumes/db
  redis_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./docker/volumes/redis
