name: ultimate-nest-dev
version: '1'
services:
  # db:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - '5433:5432' #5433 due to conflict port with existing local postgres
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #     - './resources/db:/docker-entrypoint-initdb.d'
  redis:
    image: redis
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data

  broker:
    image: bitnami/kafka:latest
    # platform: linux/amd64 # Specify amd64 platform for Kafka
    volumes:
      - kafka_data:/var/lib/kafka/data
    user: root
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

volumes:
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./volumes/db-dev
  redis_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./volumes/redis-dev
  kafka_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./volumes/kafka-dev
