name: ultimate-nest
version: '1'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432' #5433 due to conflict port with existing local postgres
    volumes:
      - './volumes/db:/var/lib/postgresql/data'
      - './resources/db:/docker-entrypoint-initdb.d'
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
