apiVersion: v1
kind: Service
metadata:
  name: external-redis
spec:
  type: ExternalName
  externalName: host.docker.internal # This resolves to your local machine
  ports:
    - port: 6379
      targetPort: 6379
